//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4234
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatusChecker.GKWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.cancer.gov/webservices/", ConfigurationName="GKWebService.GateKeeperSoap")]
    public interface GateKeeperSoap {
        
        // CODEGEN: Generating message contract since element name source from namespace http://www.cancer.gov/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cancer.gov/webservices/Request", ReplyAction="*")]
        StatusChecker.GKWebService.RequestResponse Request(StatusChecker.GKWebService.RequestRequest request);
        
        // CODEGEN: Generating message contract since element name source from namespace http://www.cancer.gov/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cancer.gov/webservices/RequestStatus", ReplyAction="*")]
        StatusChecker.GKWebService.RequestStatusResponse RequestStatus(StatusChecker.GKWebService.RequestStatusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Request", Namespace="http://www.cancer.gov/webservices/", Order=0)]
        public StatusChecker.GKWebService.RequestRequestBody Body;
        
        public RequestRequest() {
        }
        
        public RequestRequest(StatusChecker.GKWebService.RequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cancer.gov/webservices/")]
    public partial class RequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string source;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string requestID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Xml.XmlElement message;
        
        public RequestRequestBody() {
        }
        
        public RequestRequestBody(string source, string requestID, System.Xml.XmlElement message) {
            this.source = source;
            this.requestID = requestID;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestResponse", Namespace="http://www.cancer.gov/webservices/", Order=0)]
        public StatusChecker.GKWebService.RequestResponseBody Body;
        
        public RequestResponse() {
        }
        
        public RequestResponse(StatusChecker.GKWebService.RequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cancer.gov/webservices/")]
    public partial class RequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement RequestResult;
        
        public RequestResponseBody() {
        }
        
        public RequestResponseBody(System.Xml.XmlElement RequestResult) {
            this.RequestResult = RequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestStatus", Namespace="http://www.cancer.gov/webservices/", Order=0)]
        public StatusChecker.GKWebService.RequestStatusRequestBody Body;
        
        public RequestStatusRequest() {
        }
        
        public RequestStatusRequest(StatusChecker.GKWebService.RequestStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cancer.gov/webservices/")]
    public partial class RequestStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string source;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string requestID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string statusType;
        
        public RequestStatusRequestBody() {
        }
        
        public RequestStatusRequestBody(string source, string requestID, string statusType) {
            this.source = source;
            this.requestID = requestID;
            this.statusType = statusType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestStatusResponse", Namespace="http://www.cancer.gov/webservices/", Order=0)]
        public StatusChecker.GKWebService.RequestStatusResponseBody Body;
        
        public RequestStatusResponse() {
        }
        
        public RequestStatusResponse(StatusChecker.GKWebService.RequestStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cancer.gov/webservices/")]
    public partial class RequestStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement RequestStatusResult;
        
        public RequestStatusResponseBody() {
        }
        
        public RequestStatusResponseBody(System.Xml.XmlElement RequestStatusResult) {
            this.RequestStatusResult = RequestStatusResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface GateKeeperSoapChannel : StatusChecker.GKWebService.GateKeeperSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GateKeeperSoapClient : System.ServiceModel.ClientBase<StatusChecker.GKWebService.GateKeeperSoap>, StatusChecker.GKWebService.GateKeeperSoap {
        
        public GateKeeperSoapClient() {
        }
        
        public GateKeeperSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GateKeeperSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GateKeeperSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GateKeeperSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StatusChecker.GKWebService.RequestResponse StatusChecker.GKWebService.GateKeeperSoap.Request(StatusChecker.GKWebService.RequestRequest request) {
            return base.Channel.Request(request);
        }
        
        public System.Xml.XmlElement Request(string source, string requestID, System.Xml.XmlElement message) {
            StatusChecker.GKWebService.RequestRequest inValue = new StatusChecker.GKWebService.RequestRequest();
            inValue.Body = new StatusChecker.GKWebService.RequestRequestBody();
            inValue.Body.source = source;
            inValue.Body.requestID = requestID;
            inValue.Body.message = message;
            StatusChecker.GKWebService.RequestResponse retVal = ((StatusChecker.GKWebService.GateKeeperSoap)(this)).Request(inValue);
            return retVal.Body.RequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StatusChecker.GKWebService.RequestStatusResponse StatusChecker.GKWebService.GateKeeperSoap.RequestStatus(StatusChecker.GKWebService.RequestStatusRequest request) {
            return base.Channel.RequestStatus(request);
        }
        
        public System.Xml.XmlElement RequestStatus(string source, string requestID, string statusType) {
            StatusChecker.GKWebService.RequestStatusRequest inValue = new StatusChecker.GKWebService.RequestStatusRequest();
            inValue.Body = new StatusChecker.GKWebService.RequestStatusRequestBody();
            inValue.Body.source = source;
            inValue.Body.requestID = requestID;
            inValue.Body.statusType = statusType;
            StatusChecker.GKWebService.RequestStatusResponse retVal = ((StatusChecker.GKWebService.GateKeeperSoap)(this)).RequestStatus(inValue);
            return retVal.Body.RequestStatusResult;
        }
    }
}
